import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    'navigation',
    {
      type: 'link',
      label: 'Getting Started',
      href: '/getting-started',
      description: 'From an empty folder to a running platform',
    },
    {
      type: 'category',
      label: 'Philosophy',
      description: 'Why Pikku exists and the problems it solves',
      items: [
        { dirName: 'philosophy', type: 'autogenerated' },
        {
          type: 'category',
          label: 'How Pikku Compares',
          description: 'Against NestJS, Hono and Encore',
          items: [{ dirName: 'comparison', type: 'autogenerated' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Core Features',
      description: 'Functions, middleware, sessions, and error handling',
      items: [{ dirName: 'core-features', type: 'autogenerated' }],
    },
    {
      type: 'category',
      label: 'Pikku CLI',
      description: 'Code generation, filtering, and tree-shaking',
      items: [
        'pikku-cli/index',
        'pikku-cli/configuration',
        'pikku-cli/generated-files',
        'pikku-cli/tree-shaking',
        {
          type: 'category',
          label: 'Error Reference',
          description: 'What a PKUxxx code means and how to clear it',
          items: [{ dirName: 'pikku-cli/errors', type: 'autogenerated' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'The Console',
      description: 'Visual control plane for exploring and managing your app',
      items: ['console/index', 'console/getting-started', 'console/features'],
    },
    {
      type: 'category',
      label: 'Wiring',
      description: 'Connect your functions to different protocols',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'RPC',
          description: 'Function-to-function calls and external invocations',
          customProps: {
            wirings: ['rpc'],
          },
          items: [{ dirName: 'wiring/rpcs', type: 'autogenerated' }],
        },
        {
          type: 'category',
          label: 'HTTP',
          description: 'REST APIs and Server-Sent Events',
          customProps: {
            wirings: ['http'],
          },
          items: [{ dirName: 'wiring/http', type: 'autogenerated' }],
        },
        {
          type: 'category',
          label: 'Channel',
          description: 'WebSocket real-time bidirectional communication',
          customProps: {
            wirings: ['websocket'],
          },
          items: [{ dirName: 'wiring/channels', type: 'autogenerated' }],
        },
        {
          type: 'category',
          label: 'Queue',
          description: 'Background job processing',
          customProps: {
            wirings: ['queue'],
          },
          items: [{ dirName: 'wiring/queue', type: 'autogenerated' }],
        },
        {
          type: 'doc',
          id: 'wiring/scheduled-tasks',
          customProps: {
            wirings: ['cron'],
          },
        },
        {
          type: 'category',
          label: 'Workflows',
          description: 'Multi-step processes with state management',
          customProps: {
            wirings: ['workflow'],
          },
          items: [{ dirName: 'wiring/workflows', type: 'autogenerated' }],
        },
        {
          type: 'category',
          label: 'AI Agents',
          description:
            'Conversational AI with tools and multi-agent orchestration',
          customProps: {
            wirings: ['bot'],
          },
          items: [{ dirName: 'wiring/ai-agents', type: 'autogenerated' }],
        },
        {
          type: 'category',
          label: 'MCP',
          description: 'Model Context Protocol for AI agents',
          customProps: {
            wirings: ['mcp'],
          },
          items: [{ dirName: 'wiring/mcp', type: 'autogenerated' }],
        },
        {
          type: 'category',
          label: 'CLI',
          description: 'Command-line interface tools',
          customProps: {
            wirings: ['cli'],
          },
          items: [{ dirName: 'wiring/cli', type: 'autogenerated' }],
        },
        {
          type: 'category',
          label: 'Triggers',
          description: 'Event-driven subscriptions',
          customProps: {
            wirings: ['trigger'],
          },
          items: [{ dirName: 'wiring/triggers', type: 'autogenerated' }],
        },
        {
          type: 'category',
          label: 'Gateway',
          description: 'Multi-platform messaging integrations',
          customProps: {
            wirings: ['gateway'],
          },
          items: [{ dirName: 'wiring/gateway', type: 'autogenerated' }],
        },
        {
          type: 'category',
          label: 'Credentials',
          description: 'Per-user and platform-level credentials with OAuth2',
          items: [{ dirName: 'wiring/credentials', type: 'autogenerated' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      description:
        'Every export pikku gives you, by the door you import it from',
      link: { type: 'doc', id: 'api-reference/index' },
      items: [
        {
          type: 'category',
          label: 'Create a function',
          link: { type: 'doc', id: 'api-reference/create/index' },
          items: [
            'api-reference/create/function',
            'api-reference/create/setup',
          ],
        },
        {
          type: 'category',
          label: 'Enhance it',
          link: { type: 'doc', id: 'api-reference/enhance/index' },
          items: [
            'api-reference/enhance/error',
            'api-reference/enhance/middleware',
            'api-reference/enhance/secrets',
            'api-reference/enhance/variables',
            'api-reference/enhance/addon',
          ],
        },
        {
          type: 'category',
          label: 'Wire it up',
          link: { type: 'doc', id: 'api-reference/wire/index' },
          items: [
            {
              type: 'doc',
              id: 'api-reference/wire/http',
              customProps: { wirings: ['http'] },
            },
            {
              type: 'doc',
              id: 'api-reference/wire/channel',
              customProps: { wirings: ['websocket'] },
            },
            {
              type: 'doc',
              id: 'api-reference/wire/queue',
              customProps: { wirings: ['queue'] },
            },
            {
              type: 'doc',
              id: 'api-reference/wire/scheduler',
              customProps: { wirings: ['cron'] },
            },
            {
              type: 'doc',
              id: 'api-reference/wire/cli',
              customProps: { wirings: ['cli'] },
            },
            {
              type: 'doc',
              id: 'api-reference/wire/mcp',
              customProps: { wirings: ['mcp'] },
            },
            {
              type: 'doc',
              id: 'api-reference/wire/trigger',
              customProps: { wirings: ['trigger'] },
            },
            {
              type: 'doc',
              id: 'api-reference/wire/gateway',
              customProps: { wirings: ['gateway'] },
            },
          ],
        },
        {
          type: 'category',
          label: 'Guard it',
          link: { type: 'doc', id: 'api-reference/guard/index' },
          items: ['api-reference/guard/auth', 'api-reference/guard/scopes'],
        },
        {
          type: 'category',
          label: 'Orchestrate it',
          link: { type: 'doc', id: 'api-reference/orchestrate/index' },
          items: [
            {
              type: 'doc',
              id: 'api-reference/orchestrate/workflow',
              customProps: { wirings: ['workflow'] },
            },
            {
              type: 'doc',
              id: 'api-reference/orchestrate/agent',
              customProps: { wirings: ['bot'] },
            },
          ],
        },
        {
          type: 'category',
          label: 'Test it',
          link: { type: 'doc', id: 'api-reference/test/index' },
          items: ['api-reference/test/scenarios'],
        },
        'api-reference/addons',
      ],
    },
    {
      type: 'category',
      label: 'Deploy',
      description: 'Deploy your Pikku project to cloud infrastructure',
      items: [{ dirName: 'deploy', type: 'autogenerated' }],
    },
    {
      type: 'category',
      label: 'Middleware',
      description: 'Authentication and request processing middleware',
      items: [{ dirName: 'middleware', type: 'autogenerated' }],
    },
    {
      type: 'category',
      label: 'Addons',
      description: 'Reusable function packages with namespaced RPC',
      items: [{ dirName: 'addon', type: 'autogenerated' }],
    },
    {
      type: 'category',
      label: 'Advanced',
      description: 'Advanced configuration and miscellaneous topics',
      items: [
        { dirName: 'advanced', type: 'autogenerated' },
        {
          type: 'category',
          label: 'Runtimes',
          description: 'Deploy to any platform without code changes',
          items: [
            {
              type: 'doc',
              id: 'runtimes/aws-lambda',
              label: 'AWS Lambda',
              customProps: {
                wirings: ['http', 'websocket', 'cron', 'queue'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/cloudflare-functions',
              label: 'Cloudflare Workers',
              customProps: {
                wirings: ['http', 'websocket', 'cron'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/azure-functions',
              label: 'Azure Functions',
              customProps: {
                wirings: ['http', 'cron', 'queue'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/express-middleware',
              label: 'Express Middleware',
              customProps: {
                wirings: ['http', 'websocket', 'sse', 'queue'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/fastify-plugin',
              label: 'Fastify Plugin',
              customProps: {
                wirings: ['http', 'websocket', 'sse', 'queue'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/nextjs-app',
              label: 'Next.js App',
              customProps: {
                wirings: ['http', 'sse'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/uws-handler',
              label: 'uWS Handler',
              customProps: {
                wirings: ['http', 'websocket', 'sse'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/ws-handler',
              label: 'WS Handler',
              customProps: {
                wirings: ['http', 'websocket'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/bun-server',
              label: 'Bun',
              customProps: {
                wirings: ['http', 'websocket', 'mcp'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/node-http-server',
              label: 'Node HTTP',
              customProps: {
                wirings: ['http', 'mcp'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/tanstack-start',
              label: 'TanStack Start',
              customProps: {
                wirings: ['http', 'rpc'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/bullmq',
              label: 'BullMQ',
              customProps: {
                wirings: ['queue'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/pg-boss',
              label: 'PG Boss',
              customProps: {
                wirings: ['queue'],
              },
            },
            {
              type: 'doc',
              id: 'runtimes/mcp-server',
              label: 'MCP Server',
              customProps: {
                wirings: ['mcp'],
              },
            },
          ],
        },
        {
          type: 'category',
          label: 'Creating runtimes',
          description: 'Build custom adapters for any platform',
          items: [
            {
              type: 'doc',
              id: 'custom-runtimes/custom-http-runtime',
              label: 'Custom HTTP Runtime',
              customProps: {
                wirings: ['http'],
              },
            },
            {
              type: 'doc',
              id: 'custom-runtimes/custom-websocket-handler',
              label: 'Custom WebSocket Handler',
              customProps: {
                wirings: ['websocket'],
              },
            },
            {
              type: 'doc',
              id: 'custom-runtimes/custom-scheduler-handler',
              label: 'Custom Scheduler Handler',
              customProps: {
                wirings: ['cron'],
              },
            },
            {
              type: 'doc',
              id: 'custom-runtimes/custom-queue-runtime',
              label: 'Custom Queue Runtime',
              customProps: {
                wirings: ['queue'],
              },
            },
            {
              type: 'doc',
              id: 'custom-runtimes/custom-mcp-server',
              label: 'Custom MCP Server',
              customProps: {
                wirings: ['mcp'],
              },
            },
          ],
        },
        {
          type: 'category',
          label: 'Storage',
          description: 'Database backends for AI, workflows, and channels',
          items: [{ dirName: 'storage', type: 'autogenerated' }],
        },
        {
          type: 'category',
          label: 'Service Interfaces',
          description:
            'The service contracts you implement when you bring your own logger, storage or secrets',
          link: { type: 'doc', id: 'api/index' },
          items: [{ dirName: 'api', type: 'autogenerated' }],
        },
      ],
    },
  ],
};

export default sidebars;
