import typedocSidebar from "./docs/api/typedoc-sidebar.cjs";

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [{
    type: 'autogenerated',
    dirName: '.'
  }],
  api: [{
      type: "category",
      label: "Typedoc API",
      link: {
        type: "doc",
        id: "api/index",
      },
      items: typedocSidebar,
    }
]
};

export default sidebars;